<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE data [
        <!ELEMENT data (row)*>
        <!ELEMENT row (catalogue_id|key|scientific_name|title|class|family|genus|species|subspecies|collections|creation_year|absolute_url|copyright|license|authors)*>
        <!ELEMENT catalogue_id (#PCDATA)>
        <!ELEMENT key (#PCDATA)>
        <!ELEMENT scientific_name (#PCDATA)>
        <!ELEMENT title (#PCDATA)>
        <!ELEMENT class (#PCDATA)>
        <!ELEMENT family (#PCDATA)>
        <!ELEMENT genus (#PCDATA)>
        <!ELEMENT species (#PCDATA)>
        <!ELEMENT subspecies (#PCDATA)>
        <!ELEMENT collections (#PCDATA)>
        <!ELEMENT creation_year (#PCDATA)>
        <!ELEMENT absolute_url (#PCDATA)>
        <!ELEMENT copyright (#PCDATA)>
        <!ELEMENT license (#PCDATA)>
        <!ELEMENT authors (#PCDATA)>
        ]>
<data>
  <row>
    <catalogue_id>ZMB_AVES_2000-14765</catalogue_id>
    <key>7d1264cca2e93009237e</key>
    <scientific_name>Rhea americana</scientific_name>
    <title>Rhea americana</title>
    <class>Aves</class>
    <family>Rheidae</family>
    <genus>Rhea</genus>
    <species>Rhea americana</species>
    <subspecies/>
    <collections>Birds</collections>
    <creation_year>2023</creation_year>
    <absolute_url>https://portal.museumfuernaturkunde.berlin/detail/7d1264cca2e93009237e</absolute_url>
    <copyright>MfN Berlin, https://ror.org/052d1a351</copyright>
    <license>CC0 1.0 Creative Commons Public Domain Dedication</license>
    <authors>MfN Digitization</authors>
  </row>
</data>